server:
  port: 7002
spring:
  application:
    name: provider
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: hnboTAnExe
      url: jdbc:mysql://localhost:3306/chc?characterEncoding=utf-8&useSSL=false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.lming.chc.entity
  config-location: classpath:/config/mybatis-config.xml
  check-config-location: true